## Generate images from datasets and files from previous analyses containing spikes and network bursts.

In [1]:
import automea_copy
import numpy as np 
import pandas as pd 
am = automea_copy.Analysis()

In [2]:
path_to_dataset = '/Volumes/T7/automea_files_to_plot/'
dataset = 'MJ22C002-1782_DIV7.h5'
well = 'D5'

In [3]:
import os  
plots_dir = f'plots/{dataset}_{well}'
if os.path.exists(plots_dir) is False:
    os.mkdir(plots_dir)
    os.mkdir(plots_dir+'/signals')
    os.mkdir(plots_dir+'/rasters')
else:
    os.mkdir(plots_dir+'/rasters2')



In [4]:
am.path_to_dataset = path_to_dataset
am.loadh5(dataset)

In [5]:
am.signal, am.signal.shape

(array([[ 27,  23, -17, ..., -24,  31,  31],
        [-70,  15,  69, ...,  42,   4,  -8],
        [ -5, -25, -41, ..., -13, -54, -11],
        ...,
        [-17, -14,   5, ..., -17, -80,  17],
        [-36,   7,  -7, ..., -37, -19, -29],
        [  8, -20,  22, ...,   9,  73,  71]], dtype=int32),
 (237, 6000000))

In [6]:
#signal_ = np.copy(am.signal)

In [7]:
am.loadsignal(am.signal[am.wellsFromData == am.wellLabelIndexDict[well]])

In [8]:
am.model_name = 'signal30.h5'
am.loadmodel()

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



In [9]:
am.detect_threshold()
am.detect_spikes()
am.detect_reverbs(method = 'model')
am.detect_bursts()
am.detect_net('reverbs')
am.detect_net('bursts')
am.threshold, am.spikes, am.net_bursts

(array([214.14424554, 200.95122079, 221.01423154, 226.17876699,
        193.08269238, 183.83702674, 195.67306687, 196.20162996,
        207.8538975 , 205.1218292 , 186.87203155, 204.84910775]),
 [[1845,
   4262,
   4523,
   4901,
   4944,
   5030,
   5094,
   5204,
   5466,
   5525,
   5642,
   5674,
   5705,
   5799,
   5832,
   5870,
   5907,
   5950,
   6041,
   6151,
   6275,
   6316,
   6353,
   6468,
   6501,
   6721,
   6842,
   7144,
   7894,
   30334,
   34296,
   36517,
   36569,
   36616,
   37027,
   37139,
   37256,
   38112,
   55469,
   62896,
   64013,
   64965,
   65209,
   65260,
   65451,
   65547,
   65691,
   65722,
   65918,
   66118,
   66598,
   68831,
   69017,
   79288,
   87963,
   93491,
   93918,
   95450,
   96075,
   100025,
   107524,
   107670,
   108038,
   108078,
   108363,
   108412,
   108502,
   108850,
   109107,
   109455,
   109493,
   109525,
   110579,
   111195,
   111719,
   112145,
   112466,
   113024,
   140681,
   142414,
   143008,
   

In [10]:
path_to_manual_files = '/Volumes/T7/automea_files_to_plot/Examples list/RHEB_DIV07/'
spikes_manual_file = 'Timestamps_MJ22C002_1782_DIV07_D5.csv'
netbursts_manual_file = 'NetworkBursts_MJ22C002_1782_DIV07_D5.csv'

In [11]:
spikes_manual_df = pd.read_csv(path_to_manual_files + spikes_manual_file, encoding='unicode_escape')

In [12]:
spikes_manual_df

Channel ID  Channel Label  Well ID Well Label  Compound ID  \
0             191             21       22         D5  No compound   
1             191             21       22         D5  No compound   
2             191             21       22         D5  No compound   
3             191             21       22         D5  No compound   
4             191             21       22         D5  No compound   
...           ...            ...      ...        ...          ...   
65010         185             34       22         D5  No compound   
65011         185             34       22         D5  No compound   
65012         185             34       22         D5  No compound   
65013         185             34       22         D5  No compound   
65014         185             34       22         D5  No compound   

      Compound Name                                       Experiment  \
0       No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   
1       No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   
2       No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   
3       No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   
4       No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   
...             ...                                              ...   
65010   No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   
65011   No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   
65012   No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   
65013   No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   
65014   No compound  20181127_No_compound_m201118_DIV7_rescue4EB_001   

       Dose [pM] Dose Label  Timestamp [µs]  Maximum Amplitude [pV]  \
0              0    Control          426300                16212288   
1              0    Control          435100                 5066340   
2              0    Control          452400                 7569708   
3              0    Control          494500                 7808124   
4              0    Control          503100                50007756   
...          ...        ...             ...                     ...   
65010          0    Control       598999200                 7629312   
65011          0    Control       599003300                15079812   
65012          0    Control       599010600                13470504   
65013          0    Control       599039800                16391100   
65014          0    Control       599148400                 5721984   

       Minimum Amplitude [pV]  Peak-to-peak Amplitude [pV]  
0                   -25391304                     41603592  
1                   -11920800                     16987140  
2                   -14006940                     21576648  
3                   -12516840                     20324964  
4                   -59246376                    109254132  
...                       ...                          ...  
65010               -23185956                     30815268  
65011                -2264952                     17344764  
65012                -8702184                     22172688  
65013                -7092876                     23483976  
65014               -13887732                     19609716  

[65015 rows x 13 columns]

In [13]:
channel_labels = np.unique(spikes_manual_df[spikes_manual_df['Well Label'] == well]['Channel Label'].iloc[:].values)
channel_labels

array([12, 13, 21, 22, 23, 24, 31, 32, 33, 34, 42, 43])

In [14]:
spikes_manual = []
for channel_label in channel_labels:
    spikes_manual.append([])
    for index in spikes_manual_df[(spikes_manual_df['Channel Label'] == channel_label) & (spikes_manual_df['Well Label'] == well)].index:
        spikes_manual[-1].append(spikes_manual_df['Timestamp [µs]'][index]//100)

In [15]:
netbursts_manual_df = pd.read_csv(path_to_manual_files + netbursts_manual_file, encoding='unicode_escape')
netbursts_manual_df


Well ID Well Label  Compound ID Compound Name  \
0        22         D5  No compound   No compound   
1        22         D5  No compound   No compound   
2        22         D5  No compound   No compound   
3        22         D5  No compound   No compound   
4        22         D5  No compound   No compound   
..      ...        ...          ...           ...   
91       22         D5  No compound   No compound   
92       22         D5  No compound   No compound   
93       22         D5  No compound   No compound   
94       22         D5  No compound   No compound   
95       22         D5  No compound   No compound   

                                         Experiment  Dose [pM] Dose Label  \
0   20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   
1   20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   
2   20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   
3   20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   
4   20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   
..                                              ...        ...        ...   
91  20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   
92  20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   
93  20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   
94  20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   
95  20181127_No_compound_m201118_DIV7_rescue4EB_001          0    Control   

    Start timestamp [µs]  Duration [µs]  Spike Count  Spike Frequency [Hz]  
0                 494500         250600          296                98.430  
1               14255400         319800          608               158.432  
2               18646700         444100          749               140.546  
3               26212300         305800          653               177.949  
4               30838400         265700          603               189.123  
..                   ...            ...          ...                   ...  
91             573895000         311100          216                57.859  
92             578123900         375300          725               160.982  
93             585406500         363400          487               111.677  
94             591906400         390700          690               147.172  
95             598675200         379000          734               161.390  

[96 rows x 11 columns]

In [16]:
net_manual = []
for index in netbursts_manual_df[netbursts_manual_df['Well Label']==well].index:
    start_ts = netbursts_manual_df['Start timestamp [µs]'][index]
    duration = netbursts_manual_df['Duration [µs]'][index]
    net_manual.append([start_ts//100, (start_ts+duration)//100])

In [17]:
duration = 60
duration_shorter = 5

for i, start_time in enumerate(np.random.randint(0,500,size=3)):

    end_time = start_time + duration

    am.plot_raster(am.spikes, net_bursts = am.net_reverbs, start_time = start_time, end_time = end_time, 
                   save = f'{plots_dir}/rasters2/raster_start{start_time}_duration{duration}_allwell_prednetreverbs.eps', show = False)
    am.plot_raster(am.spikes, net_bursts = net_manual, start_time = start_time, end_time = end_time, 
                   save = f'{plots_dir}/rasters2/raster_start{start_time}_duration{duration}_allwell_manual.eps', show = False)

    for j in range(5):
        start_time_shorter = start_time + np.random.randint(0,95)
        channel_random  = np.random.randint(len(am.signal))
        end_time_shorter = start_time_shorter + duration_shorter
        am.plot_raster(am.spikes[channel_random], net_bursts = am.net_reverbs, start_time = start_time_shorter, end_time = end_time_shorter, 
                        save = f'{plots_dir}/rasters2/raster_start{start_time}_duration{duration}_zoomedstart{start_time+start_time_shorter}_zoomedduration{duration_shorter}_prednetreverbs.eps', show = False)
        am.plot_raster(am.spikes[channel_random], net_bursts = net_manual, start_time = start_time_shorter, end_time = end_time_shorter,
                        save = f'{plots_dir}/rasters2/raster_start{start_time}_duration{duration}_zoomedstart{start_time+start_time_shorter}_zoomedduration{duration_shorter}_manual.eps', show = False)


In [19]:
duration_shorter = 5

for _ in range(20):
    random_net = am.net_reverbs[np.random.randint(len(am.net_reverbs))]
    middle_of_net = random_net[0] + ((random_net[-1] - random_net[0])/2)
    start_time = middle_of_net/am.samplingFreq - 2.5
    channel_random  = np.random.randint(len(am.signal))


    am.plot_window(am.signal[channel_random], start_time=start_time, duration=duration_shorter,
                    threshold=am.threshold[channel_random], spikes = am.spikes[channel_random],
                    bursts=am.net_reverbs, net_bursts=net_manual, yunits = 'V', show = False)#,
                    #save = f'{plots_dir}/signals/signal_channel{channel_random}_start{start_time}_duration5.eps')
